### ISSUE TITLE
Javadocs and other question

### ISSUE THREAD

**Issue by tophstar** [mariuswatz/modelbuilderMk2#1]
Hello,

First off, thank you for creating this library and continuing your work.  As a 3D scanner/printer enthusiast this library has been incredibly helpful!  But I do have a few questions.

I have been using the older unlekker modelbuilder version, but I would like to update to this version.  Before I do that, I would like to be able to look over an Javadoc for the library.  I have not been able to successfully find a Javadoc for modelbuilder MK2.  Would you be able to point me in the right direction?

Also, does this version supports creating colored UGeo faces?

Best Regards,
Toph

**Comment by mariuswatz** [comment]
Javadocs are exported and included with the Processing-ready ZIP archive builds. Just download export/modelbuilderMk2-0152-20140803.zip or whichever is most recent. "doc-modelbuilderMk2" contains the Javadoc, source is included in "src-modelbuilderMk2".

UGeo supports color in UFace triangles (see UFace.setColor()), but only for drawing. Unfortunately, I haven't had time to find a solution to exporting colored models for 3D printing.
